//! Safe communicator: rendezvous + lifecycle around `ncclComm_t`.
//!
//! A `Communicator` is the handle every collective runs against. Creating one is
//! a two-step handshake:
//!   1. Rank 0 calls `UniqueId::generate()` and publishes the 128-byte id to the
//!      other ranks out-of-band (the Python launcher does this over TCP).
//!   2. Every rank calls `Communicator::init_rank(id, world_size, rank)`.
//!
//! NCCL then discovers the fastest transport it can between every pair of ranks
//! on its own: NVLink/NVSwitch inside a node, and the network (GPUDirect-TCPX /
//! RoCE / IB) across nodes. gradsync does not pick the transport; it reports what
//! NCCL chose via `topology`.

use crate::error::{Error, Result};
use crate::nccl;

/// The out-of-band bootstrap id, generated by rank 0 and shared with all ranks.
#[derive(Clone, Copy)]
pub struct UniqueId(pub(crate) nccl::ncclUniqueId);

impl UniqueId {
    /// Rank 0 generates this and broadcasts the bytes to every other rank.
    pub fn generate() -> Result<Self> {
        #[cfg(feature = "nccl")]
        {
            let mut id = nccl::ncclUniqueId::default();
            let rc = unsafe { nccl::ncclGetUniqueId(&mut id) };
            check(rc)?;
            Ok(UniqueId(id))
        }
        #[cfg(not(feature = "nccl"))]
        {
            Err(Error::StubBuild)
        }
    }

    /// Serialize to the 128 raw bytes so the launcher can ship it over TCP.
    pub fn as_bytes(&self) -> [u8; 128] {
        let mut out = [0u8; 128];
        for (o, b) in out.iter_mut().zip(self.0.internal.iter()) {
            *o = *b as u8;
        }
        out
    }

    /// Reconstruct on a non-zero rank from the bytes received over the network.
    pub fn from_bytes(bytes: &[u8; 128]) -> Self {
        let mut id = nccl::ncclUniqueId::default();
        for (slot, b) in id.internal.iter_mut().zip(bytes.iter()) {
            *slot = *b as std::os::raw::c_char;
        }
        UniqueId(id)
    }
}

/// A live NCCL communicator bound to one GPU on one rank.
pub struct Communicator {
    #[allow(dead_code)]
    handle: nccl::ncclComm_t,
    world_size: i32,
    rank: i32,
    device: i32,
}

impl Communicator {
    /// Join the collective group. `device` is the local CUDA device ordinal this
    /// rank drives (0 on a single-GPU-per-process launch).
    pub fn init_rank(id: &UniqueId, world_size: i32, rank: i32, device: i32) -> Result<Self> {
        #[cfg(feature = "nccl")]
        {
            let mut handle: nccl::ncclComm_t = std::ptr::null_mut();
            unsafe {
                let rc = nccl::cudaSetDevice(device);
                if rc != 0 {
                    return Err(Error::Cuda(rc));
                }
                let rc = nccl::ncclCommInitRank(&mut handle, world_size, id.0, rank);
                check(rc)?;
            }
            Ok(Communicator {
                handle,
                world_size,
                rank,
                device,
            })
        }
        #[cfg(not(feature = "nccl"))]
        {
            let _ = (id, world_size, rank, device);
            Err(Error::StubBuild)
        }
    }

    #[inline]
    pub(crate) fn raw(&self) -> nccl::ncclComm_t {
        self.handle
    }
    pub fn world_size(&self) -> i32 {
        self.world_size
    }
    pub fn rank(&self) -> i32 {
        self.rank
    }
    pub fn device(&self) -> i32 {
        self.device
    }
}

impl Drop for Communicator {
    fn drop(&mut self) {
        #[cfg(feature = "nccl")]
        unsafe {
            // Best effort; nothing actionable if teardown fails.
            let _ = nccl::ncclCommDestroy(self.handle);
        }
    }
}

pub(crate) fn check(rc: nccl::ncclResult_t) -> Result<()> {
    if rc == nccl::NCCL_SUCCESS {
        return Ok(());
    }
    #[cfg(feature = "nccl")]
    {
        let msg = unsafe {
            let ptr = nccl::ncclGetErrorString(rc);
            std::ffi::CStr::from_ptr(ptr).to_string_lossy().into_owned()
        };
        Err(Error::Nccl { code: rc, msg })
    }
    #[cfg(not(feature = "nccl"))]
    {
        Err(Error::Nccl {
            code: rc,
            msg: "nccl feature disabled".into(),
        })
    }
}
